Add participant self-description
agera-edc/MinimumViableDataspace pull request #267
Opened 2022-08-17 09:55 UTC by bscholtes1A

## What this PR changes/adds

Generate a Gaia-X Self-Description based on a template for each participant and inject it into the associated Identity Hub.

## Why it does that

Each dataspace participant should have its own Self-Description.

## Linked Issue(s)

#186 

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [ ] formatted title correctly?

2022-08-17 17:40 UTC, algattik requested changes

2022-08-17 17:40 UTC, algattik commented on deployment/terraform/participant/main.tf
> +  static_website {}
why `static_website`? This will create a public HTTP endpoint, but does not seem to be needed here

2022-08-17 17:40 UTC, algattik commented on .github/workflows/deploy.yaml
> +      - name: 'Generate Gaia-X Self-Description'
why introduce jinja2 instead of using Terraform to generate the document as we do for others?
This is also slow (15s)

2022-08-17 17:40 UTC, algattik commented on system-tests/src/test/java/org/eclipse/dataspaceconnector/system/tests/identityhub/IdentityHubIntegrationTest.java
> +        assertThat(value).isNotNull();
add `as(key)` to make error message clear on failure?

2022-08-18 10:10 UTC, algattik approved these changes
I assume:
- integration tests will follow in a next PR?
- you have tested manually that this PR produces the expected file

Would be good to answer that in the PR description

2022-08-18 10:15 UTC, bscholtes1A commented
> I assume:
> 
> * integration tests will follow in a next PR?
> * you have tested manually that this PR produces the expected file
> 
> Would be good to answer that in the PR description

I have completed an existing integration test, https://github.com/agera-edc/MinimumViableDataspace/pull/267/files#diff-1c16050e7a1661aae3abbf2aec3894483d4b82036dfcb665f3b937760c2f841d, which ensure the file is properly exposed trough the Identity Hub.

2022-08-18 13:45 UTC, merged